"""dealer_branches: change parent_dealer_id to dealer_id

Revision ID: 7ca3c6718423
Revises: cf849e2ad341
Create Date: 2024-11-05 13:57:08.995000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca3c6718423'
down_revision: Union[str, None] = 'cf849e2ad341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('va_dealer_branches', sa.Column('dealer_id', sa.String(length=255), nullable=False))
    op.drop_constraint('va_dealer_branches_parent_dealer_id_fkey', 'va_dealer_branches', type_='foreignkey')
    op.create_foreign_key(None, 'va_dealer_branches', 'va_dealers', ['dealer_id'], ['id'])
    op.drop_column('va_dealer_branches', 'parent_dealer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('va_dealer_branches', sa.Column('parent_dealer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'va_dealer_branches', type_='foreignkey')
    op.create_foreign_key('va_dealer_branches_parent_dealer_id_fkey', 'va_dealer_branches', 'va_dealers', ['parent_dealer_id'], ['id'])
    op.drop_column('va_dealer_branches', 'dealer_id')
    # ### end Alembic commands ###
